server:
  port: 83
  servlet:
    context-path: /others
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    # Tomcat启动初始化的线程数，默认值25
    threads:
      max: 300
      min-spare: 30

# 日志配置
logging:
  level:
    com.wayn: debug
    org.springframework: info
    com.baomidou: info

# spring
spring:
  thymeleaf:
    suffix: .html
    cache: false
    encoding: UTF-8
  profiles:
    active: dev
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false

# wayn配置
wayn:
  uploadDir: E:/wayn/upload
  ssoServerUrl: http://127.0.0.1:82/ssoserver
  currentServerUrl: http://127.0.0.1:83/others
  xssFilter:
    excludeUrls: /**/*.js,/**/*.css,/favicon.ico,/fonts/*,/plugin/*



